### ISSUE TITLE
Error while running USEquityPricingLoader

### ISSUE THREAD

**Issue by igor17400** [stefan-jansen/zipline-reloaded#60]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Mac M1
* Python Version: Python 3.8.12
* Python Bitness: 64
* How did you install Zipline: conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded
* Python packages: #
# Name                    Version                   Build  Channel
alembic                   1.7.4              pyhd8ed1ab_0    conda-forge
appnope                   0.1.0                 py38_1001    anaconda
argon2-cffi               20.1.0           py38haf1e3a3_1    anaconda
async_generator           1.10                       py_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
bcolz-zipline             1.2.4            py38hf1f42d3_0    ml4t
bleach                    3.2.1                      py_0    anaconda
blosc                     1.21.0               he49afe7_0    conda-forge
bottleneck                1.3.2            py38hbe852b5_4    conda-forge
brotlipy                  0.7.0           py38h96a0964_1001    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.17.2               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.14.12              he60d9cb_2  
certifi                   2021.10.8        py38h50d1736_0    conda-forge
cffi                      1.14.6           py38h9688ba1_0    conda-forge
chardet                   4.0.0            py38h50d1736_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38h50d1736_0    conda-forge
cryptography              35.0.0           py38hcc27614_0    conda-forge
dbus                      1.13.18              h18a8e69_0    anaconda
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    anaconda
empyrical-reloaded        0.5.8                    py38_0    ml4t
entrypoints               0.3                      py38_0    anaconda
expat                     2.2.10               hb1e8313_2    anaconda
fontconfig                2.12.6               h9850fc5_0    anaconda
freetype                  2.8                  h12048fb_1    anaconda
gettext                   0.19.8.1             h15daf44_3    anaconda
glib                      2.66.1               h9bbe63b_0    anaconda
graphite2                 1.3.14               h38d11af_0    anaconda
graphviz                  2.40.1               h0a44026_0    anaconda
greenlet                  1.1.2            py38ha048514_0    conda-forge
h5py                      3.4.0           nompi_py38h9f21798_101    conda-forge
harfbuzz                  1.7.6                h171471c_1  
hdf5                      1.12.1          nompi_h2f0ef1a_100    conda-forge
icu                       58.2                 h0a44026_3    anaconda
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.8.1            py38h50d1736_0    conda-forge
importlib_metadata        1.5.0                    py38_0    anaconda
importlib_resources       5.2.2              pyhd8ed1ab_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py38h5ca1d4c_0    anaconda
ipython                   7.18.1           py38h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py38_0    anaconda
ipywidgets                7.5.1                      py_1    anaconda
iso3166                   2.0.2              pyhd8ed1ab_0    conda-forge
iso4217                   1.6.20180829               py_0    conda-forge
jedi                      0.18.0           py38hecd8cb5_1  
jinja2                    2.11.2                     py_0    anaconda
jpeg                      9b                   he5867d9_2    anaconda
jsonschema                3.2.0                      py_2    anaconda
jupyter                   1.0.0                    py38_7    anaconda
jupyter_client            6.1.7                      py_0    anaconda
jupyter_console           6.2.0                      py_0    anaconda
jupyter_core              4.6.3                    py38_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
krb5                      1.19.2               hcfbf3a7_2    conda-forge
libblas                   3.9.0           12_osx64_openblas    conda-forge
libcblas                  3.9.0           12_osx64_openblas    conda-forge
libcurl                   7.79.1               hf45b732_1    conda-forge
libcxx                    12.0.0               h2f01273_0  
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2  
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           12_osx64_openblas    conda-forge
libnghttp2                1.43.0               h6f36284_1    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               ha441bb4_0    anaconda
libsodium                 1.0.18               h1de35cc_0    anaconda
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.1.0                hcb84e12_1    anaconda
libxml2                   2.9.10               h7cdb67c_3    anaconda
libxslt                   1.1.34               h83b36ba_0    anaconda
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
logbook                   1.5.3                    py38_0    ml4t
lru-dict                  1.1.7            py38h96a0964_0    conda-forge
lxml                      4.6.3            py38h6ea4786_0    conda-forge
lz4-c                     1.9.2                h79c402e_3    anaconda
mako                      1.1.5              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h96a0964_0    conda-forge
mistune                   0.8.4           py38h1de35cc_1001    anaconda
mock                      4.0.3            py38h50d1736_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.1                      py_0    anaconda
nbconvert                 6.0.7                    py38_0    anaconda
nbformat                  5.0.8                      py_0    anaconda
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.4.1                      py_0    anaconda
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
notebook                  6.1.4                    py38_0    anaconda
numexpr                   2.7.3            py38ha53d530_0    conda-forge
numpy                     1.21.2           py38h49b9922_0    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 20.4                       py_0    anaconda
pandas                    1.2.5            py38h1f261ad_0    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandoc                    2.11                 h0dc7051_0    anaconda
pandocfilters             1.4.2                    py38_1    anaconda
pango                     1.41.0               h3bae10e_0    anaconda
parso                     0.8.0                      py_0    anaconda
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.44                 hb1e8313_0    anaconda
pexpect                   4.8.0                    py38_1    anaconda
pickleshare               0.7.5                 py38_1001    anaconda
pip                       21.2.4           py38hecd8cb5_0  
pixman                    0.40.0               haf1e3a3_0    anaconda
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.8                      py_0    anaconda
prompt_toolkit            3.0.8                         0    anaconda
ptyprocess                0.6.0                    py38_0    anaconda
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    anaconda
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py38h655552a_2    anaconda
pyrsistent                0.17.3           py38haf1e3a3_0    anaconda
pysocks                   1.7.1            py38h50d1736_3    conda-forge
pytables                  3.6.1            py38h5215406_4    conda-forge
python                    3.8.12               h88f2d9e_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.16               pyhd3eb1b0_1  
python-interface          1.6.0                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyzmq                     19.0.2           py38hb1e8313_1    anaconda
qt                        5.9.7                h468cd18_1    anaconda
qtconsole                 4.7.7                      py_0    anaconda
qtpy                      1.9.0                      py_0    anaconda
readline                  8.1                  h9ed2024_0  
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
scipy                     1.7.1            py38hd329d04_0    conda-forge
send2trash                1.5.0                    py38_0    anaconda
setuptools                58.0.4           py38hecd8cb5_0  
sip                       4.19.8           py38h0a44026_0    anaconda
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.25           py38h96a0964_0    conda-forge
sqlite                    3.36.0               hce871da_0  
statsmodels               0.13.0           py38hbe852b5_0    conda-forge
ta-lib                    0.4.19           py38h7772d1b_0    ml4t
terminado                 0.9.1                    py38_0    anaconda
testpath                  0.4.4                      py_0    anaconda
tk                        8.6.11               h7bc2e8c_0  
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py38h1de35cc_1    anaconda
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
traitlets                 5.0.5                      py_0    anaconda
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py38_1    anaconda
wheel                     0.37.0             pyhd3eb1b0_1  
widgetsnbextension        3.5.1                    py38_0    anaconda
xz                        5.2.5                h1de35cc_0  
yfinance                  0.1.63                     py_0    ml4t
zeromq                    4.3.3                hb1e8313_3    anaconda
zipline-reloaded          2.1.1            py38hf1f42d3_0    ml4t
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.4                h1990bb4_3    anaconda

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

I'm trying to run the following code
```
from zipline.pipeline.loaders import USEquityPricingLoader

# Set the dataloader
pricing_loader = USEquityPricingLoader(bundle_data.equity_daily_bar_reader, bundle_data.adjustment_reader,)

```

However, I'm receiving the error `TypeError: __init__() missing 1 required positional argument: 'fx_reader'`

* What did you expect to happen?
I expected the code to run succesfully

* What happened instead?
A TypeError happened instead.

Here is how you can reproduce this issue on your machine:
Just run the code snipped above.

Sincerely,
Igor Lima

**Comment by igor17400** [comment]
I believed I've fixed the problem by running the code below

`pricing_loader = USEquityPricingLoader.without_fx(bundle_data.equity_daily_bar_reader, bundle_data.adjustment_reader,)`

**Comment by BinhKieu82** [comment]
Hi Igor, hope you are well with your zipline! I previously got the same issue with _'fx_reader'_. After using your suggestion `'.without_fx'`, it raises another issue as below
```
TypeError                                 Traceback (most recent call last)
<ipython-input-7-e94c37f0c630> in <module>()
     11 engine = SimplePipelineEngine(get_loader=choose_loader,
     12                               calendar=trading_calendar.all_sessions,
---> 13                               asset_finder=bundle_data.asset_finder)
     14 

TypeError: __init__() got an unexpected keyword argument 'calendar'
```
I've taken some googling but no hope so far. Would you have any idea on that. I'm using **zipline 1.4.1**, it works well with zipline 1.2.0
Thanks in advance!

**Comment by MBounouar** [comment]
@BinhKieu82 ,  this is `zipline-reloaded` not `zipline` ;-) ,  if you look at the doc [SimplePipelineEngine](https://zipline.ml4trading.io/api-reference.html?highlight=simplepipeline#zipline.pipeline.engine.SimplePipelineEngine) and the error message, `calendar` is not a valid parameter (anymore).

**Comment by stefan-jansen** [comment]
Closing due to lack of activity.
